<a href="https://colab.research.google.com/github/salsilsulselsol/Associate-Data-Scientist-Python-Nasional-Notes-Experiment/blob/main/06_numpy_numerical_computing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Module 06: Numerical Computing with NumPy
**Course:** Associate Data Scientist + Python - Nasional  
**Objective:** Efficiently handling N-dimensional arrays (ndarrays) and performing high-performance numerical operations.

## 1. Introduction to NumPy
NumPy (Numerical Python) is optimized in C, making it significantly faster than standard Python lists. It is the backbone for Pandas, Scikit-learn, and TensorFlow.

### 1.1 Creating Arrays
Arrays can be created from lists or using built-in functions for specific distributions.

In [1]:
import numpy as np

# Creating from a list
arr_2d = np.array([[1, 2], [3, 4]])

# Specialized creation functions
zeros_arr = np.zeros((3, 3))              # 3x3 array of 0.0
ones_arr = np.ones((2, 3))               # 2x3 array of 1.0
random_arr = np.random.rand(2, 2)        # Random values [0, 1)
range_arr = np.arange(0, 10, 2)          # [0, 2, 4, 6, 8]
linspace_arr = np.linspace(0, 1, 5)      # 5 values evenly spaced from 0 to 1

# Array Attributes
print(f"Shape: {arr_2d.shape}")
print(f"Size: {arr_2d.size}")
print(f"Data Type: {arr_2d.dtype}")

Shape: (2, 2)
Size: 4
Data Type: int64


## 2. Array Operations
Operations in NumPy are performed **element-wise**, allowing for concise and fast calculations.

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Arithmetic
print(f"Addition: {a + b}")
print(f"Multiplication: {a * b}")

# Indexing and Slicing
arr = np.array([10, 20, 30, 40, 50])
print(f"Slice (index 1 to 3): {arr[1:4]}")
print(f"Last element: {arr[-1]}")

Addition: [5 7 9]
Multiplication: [ 4 10 18]
Slice (index 1 to 3): [20 30 40]
Last element: 50


## 3. Shape Manipulation
Changing data dimensions is crucial for preparing inputs for Deep Learning models.

In [3]:
# Reshaping
arr_1d = np.arange(6)
reshaped = arr_1d.reshape(2, 3)

# Stacking and Concatenation
v_stack = np.vstack((a, b))    # Vertical stack
h_stack = np.hstack((a, b))    # Horizontal stack
concat = np.concatenate((a, b))

print(f"Reshaped Matrix:\n{reshaped}")

Reshaped Matrix:
[[0 1 2]
 [3 4 5]]


## 4. Mathematical and Statistical Functions
NumPy provides powerful tools for descriptive statistics and matrix operations.

In [4]:
data = np.array([[1, 2], [3, 4]])

# Statistics
print(f"Mean: {np.mean(data)}")
print(f"Median: {np.median(data)}")
print(f"Standard Deviation: {np.std(data)}")

# Linear Algebra (Matrix Multiplication)
# Essential for calculating transformations and weights
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
dot_product = np.dot(matrix_a, matrix_b)

print(f"Dot Product result:\n{dot_product}")

Mean: 2.5
Median: 2.5
Standard Deviation: 1.118033988749895
Dot Product result:
[[19 22]
 [43 50]]


## 5. Practical Use Case: Axis-based Calculations
In Data Science, we often need to calculate metrics across rows (axis 1) or columns (axis 0).

In [5]:
# Simulating 5 students with scores in 3 subjects
np.random.seed(42)
scores = np.random.rand(5, 3) * 100

# Median score for each subject (Column-wise)
subject_medians = np.median(scores, axis=0)

# Average score for each student (Row-wise)
student_averages = np.mean(scores, axis=1)

print(f"Subject Medians: {subject_medians}")
print(f"Student Averages: {student_averages}")

Subject Medians: [59.86584842 21.23391107 60.11150117]
Student Averages: [68.57494557 30.3557215  50.84582566 56.61889748 40.88689062]
